apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - envsubst '$(DOMAIN)_NAME' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $(){!}; nginx -s reload; done & nginx -g 'daemon off;'
          image: nginx:-
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 5602
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/syslog
              name: nginx-cm0
            - mountPath: /var/log/nginx
              name: nginx-cm1
            - mountPath: /var/www/certbot
              name: nginx-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: nginx-cm0
          name: nginx-cm0
        - configMap:
            name: nginx-cm1
          name: nginx-cm1
        - name: nginx-claim2
          persistentVolumeClaim:
            claimName: nginx-claim2
            readOnly: true
